# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_proto/image-mood-classification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_proto/image-mood-classification.proto',
  package='YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX',
  syntax='proto3',
  serialized_pb=_b('\n*test_proto/image-mood-classification.proto\x12 YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX\"8\n\x0bImageTagSet\x12\r\n\x05image\x18\x01 \x03(\x03\x12\x0b\n\x03tag\x18\x02 \x03(\t\x12\r\n\x05score\x18\x03 \x03(\x01\x32q\n\x05Model\x12h\n\x08\x63lassify\x12-.YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSet\x1a-.YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSetb\x06proto3')
)




_IMAGETAGSET = _descriptor.Descriptor(
  name='ImageTagSet',
  full_name='YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSet.image', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tag', full_name='YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSet.tag', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSet.score', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['ImageTagSet'] = _IMAGETAGSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageTagSet = _reflection.GeneratedProtocolMessageType('ImageTagSet', (_message.Message,), dict(
  DESCRIPTOR = _IMAGETAGSET,
  __module__ = 'test_proto.image_mood_classification_pb2'
  # @@protoc_insertion_point(class_scope:YKhGXjKWHYsPwKJFfEPnmoHOkDkPKBxX.ImageTagSet)
  ))
_sym_db.RegisterMessage(ImageTagSet)


# @@protoc_insertion_point(module_scope)
