# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: probe-testnested-100.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='probe-testnested-100.proto',
  package='nestedmessage',
  syntax='proto3',
  serialized_pb=_b('\n\x1aprobe-testnested-100.proto\x12\rnestedmessage\",\n\tNestInner\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"=\n\tNestOuter\x12\x0b\n\x03tag\x18\x01 \x01(\t\x12#\n\x01i\x18\x02 \x01(\x0b\x32\x18.nestedmessage.NestInnerb\x06proto3')
)




_NESTINNER = _descriptor.Descriptor(
  name='NestInner',
  full_name='nestedmessage.NestInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='nestedmessage.NestInner.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='nestedmessage.NestInner.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='nestedmessage.NestInner.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=89,
)


_NESTOUTER = _descriptor.Descriptor(
  name='NestOuter',
  full_name='nestedmessage.NestOuter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag', full_name='nestedmessage.NestOuter.tag', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='i', full_name='nestedmessage.NestOuter.i', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=152,
)

_NESTOUTER.fields_by_name['i'].message_type = _NESTINNER
DESCRIPTOR.message_types_by_name['NestInner'] = _NESTINNER
DESCRIPTOR.message_types_by_name['NestOuter'] = _NESTOUTER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NestInner = _reflection.GeneratedProtocolMessageType('NestInner', (_message.Message,), dict(
  DESCRIPTOR = _NESTINNER,
  __module__ = 'probe_testnested_100_pb2'
  # @@protoc_insertion_point(class_scope:nestedmessage.NestInner)
  ))
_sym_db.RegisterMessage(NestInner)

NestOuter = _reflection.GeneratedProtocolMessageType('NestOuter', (_message.Message,), dict(
  DESCRIPTOR = _NESTOUTER,
  __module__ = 'probe_testnested_100_pb2'
  # @@protoc_insertion_point(class_scope:nestedmessage.NestOuter)
  ))
_sym_db.RegisterMessage(NestOuter)


# @@protoc_insertion_point(module_scope)
