# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: probe_testimage_100_proto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='probe_testimage_100_proto.proto',
  package='whatisthisforagain',
  syntax='proto3',
  serialized_pb=_b('\n\x1fprobe_testimage_100_proto.proto\x12\x12whatisthisforagain\"*\n\x13TransformedImagePNG\x12\x13\n\x0bimagebinary\x18\x01 \x01(\x0c\"+\n\x14TransformedImageJPEG\x12\x13\n\x0bimagebinary\x18\x01 \x01(\x0c\x62\x06proto3')
)




_TRANSFORMEDIMAGEPNG = _descriptor.Descriptor(
  name='TransformedImagePNG',
  full_name='whatisthisforagain.TransformedImagePNG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imagebinary', full_name='whatisthisforagain.TransformedImagePNG.imagebinary', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=97,
)


_TRANSFORMEDIMAGEJPEG = _descriptor.Descriptor(
  name='TransformedImageJPEG',
  full_name='whatisthisforagain.TransformedImageJPEG',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imagebinary', full_name='whatisthisforagain.TransformedImageJPEG.imagebinary', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['TransformedImagePNG'] = _TRANSFORMEDIMAGEPNG
DESCRIPTOR.message_types_by_name['TransformedImageJPEG'] = _TRANSFORMEDIMAGEJPEG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransformedImagePNG = _reflection.GeneratedProtocolMessageType('TransformedImagePNG', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFORMEDIMAGEPNG,
  __module__ = 'probe_testimage_100_proto_pb2'
  # @@protoc_insertion_point(class_scope:whatisthisforagain.TransformedImagePNG)
  ))
_sym_db.RegisterMessage(TransformedImagePNG)

TransformedImageJPEG = _reflection.GeneratedProtocolMessageType('TransformedImageJPEG', (_message.Message,), dict(
  DESCRIPTOR = _TRANSFORMEDIMAGEJPEG,
  __module__ = 'probe_testimage_100_proto_pb2'
  # @@protoc_insertion_point(class_scope:whatisthisforagain.TransformedImageJPEG)
  ))
_sym_db.RegisterMessage(TransformedImageJPEG)


# @@protoc_insertion_point(module_scope)
